CREATE DATABASE IF NOT EXISTS WEATHER_ANALYTICS;
CREATE SCHEMA IF NOT EXISTS WEATHER_ANALYTICS.RAW;
CREATE SCHEMA IF NOT EXISTS WEATHER_ANALYTICS.ANALYTICS;
CREATE FILE FORMAT IF NOT EXISTS WEATHER_ANALYTICS.RAW.PARQUET_FORMAT TYPE = PARQUET;

CREATE TABLE IF NOT EXISTS WEATHER_ANALYTICS.RAW.WEATHER_DAILY (
  CITY VARCHAR,
  WEATHER_DATE DATE,
  TEMPERATURE_MAX_C NUMBER(8,2),
  TEMPERATURE_MIN_C NUMBER(8,2),
  PRECIPITATION_MM NUMBER(10,2),
  INGESTED_AT TIMESTAMP_TZ
);
